/**
 * Centralized Permission Constants for LabFlow System
 * 
 * Permission Naming Convention:
 * - MODULE_ACTION_RESOURCE
 * - Example: PATIENTS_VIEW_ALL, BILLING_CREATE_INVOICE
 * 
 * Modules: PATIENTS, TESTS, RESULTS, BILLING, INVENTORY, REPORTS, USERS, SETTINGS, ADMIN
 * Actions: VIEW, CREATE, UPDATE, DELETE, EXPORT, IMPORT, APPROVE, PRINT
 * Resources: ALL, OWN, ASSIGNED, DEPARTMENT
 */

export const PERMISSIONS = {
  // Patient Management Permissions
  PATIENTS_VIEW_ALL: 'patients.view.all',
  PATIENTS_VIEW_OWN: 'patients.view.own',
  PATIENTS_VIEW_ASSIGNED: 'patients.view.assigned',
  PATIENTS_CREATE: 'patients.create',
  PATIENTS_UPDATE_ALL: 'patients.update.all',
  PATIENTS_UPDATE_OWN: 'patients.update.own',
  PATIENTS_DELETE: 'patients.delete',
  PATIENTS_EXPORT: 'patients.export',
  PATIENTS_IMPORT: 'patients.import',
  PATIENTS_VIEW_MEDICAL_HISTORY: 'patients.view.medical_history',
  PATIENTS_MERGE: 'patients.merge',

  // Test Management Permissions
  TESTS_VIEW_ALL: 'tests.view.all',
  TESTS_VIEW_ASSIGNED: 'tests.view.assigned',
  TESTS_CREATE_ORDER: 'tests.create.order',
  TESTS_UPDATE_ORDER: 'tests.update.order',
  TESTS_CANCEL_ORDER: 'tests.cancel.order',
  TESTS_APPROVE_ORDER: 'tests.approve.order',
  TESTS_MANAGE_CATALOG: 'tests.manage.catalog',
  TESTS_CREATE_PANEL: 'tests.create.panel',
  TESTS_UPDATE_PRICING: 'tests.update.pricing',
  TESTS_VIEW_PRICING: 'tests.view.pricing',
  TESTS_STAT_ORDER: 'tests.stat.order',
  TESTS_BATCH_ORDER: 'tests.batch.order',

  // Sample Management Permissions
  SAMPLES_COLLECT: 'samples.collect',
  SAMPLES_RECEIVE: 'samples.receive',
  SAMPLES_REJECT: 'samples.reject',
  SAMPLES_PROCESS: 'samples.process',
  SAMPLES_TRACK: 'samples.track',
  SAMPLES_PRINT_BARCODE: 'samples.print.barcode',
  SAMPLES_ALIQUOT: 'samples.aliquot',
  SAMPLES_DISPOSE: 'samples.dispose',
  SAMPLES_VIEW_ALL: 'samples.view.all',
  SAMPLES_UPDATE_STATUS: 'samples.update.status',

  // Results Management Permissions
  RESULTS_VIEW_ALL: 'results.view.all',
  RESULTS_VIEW_ASSIGNED: 'results.view.assigned',
  RESULTS_ENTER: 'results.enter',
  RESULTS_UPDATE: 'results.update',
  RESULTS_VALIDATE: 'results.validate',
  RESULTS_APPROVE: 'results.approve',
  RESULTS_REJECT: 'results.reject',
  RESULTS_PRINT: 'results.print',
  RESULTS_EMAIL: 'results.email',
  RESULTS_AMEND: 'results.amend',
  RESULTS_VIEW_CRITICAL: 'results.view.critical',
  RESULTS_ACKNOWLEDGE_CRITICAL: 'results.acknowledge.critical',

  // Billing & Insurance Permissions
  BILLING_VIEW_ALL: 'billing.view.all',
  BILLING_VIEW_OWN: 'billing.view.own',
  BILLING_CREATE_INVOICE: 'billing.create.invoice',
  BILLING_UPDATE_INVOICE: 'billing.update.invoice',
  BILLING_CANCEL_INVOICE: 'billing.cancel.invoice',
  BILLING_APPLY_DISCOUNT: 'billing.apply.discount',
  BILLING_PROCESS_PAYMENT: 'billing.process.payment',
  BILLING_PROCESS_REFUND: 'billing.process.refund',
  BILLING_VIEW_REPORTS: 'billing.view.reports',
  BILLING_MANAGE_INSURANCE: 'billing.manage.insurance',
  BILLING_SUBMIT_CLAIM: 'billing.submit.claim',
  BILLING_MANAGE_PRICING: 'billing.manage.pricing',
  BILLING_WRITE_OFF: 'billing.write.off',

  // Inventory Management Permissions
  INVENTORY_VIEW_ALL: 'inventory.view.all',
  INVENTORY_VIEW_DEPARTMENT: 'inventory.view.department',
  INVENTORY_ADD_STOCK: 'inventory.add.stock',
  INVENTORY_UPDATE_STOCK: 'inventory.update.stock',
  INVENTORY_TRANSFER_STOCK: 'inventory.transfer.stock',
  INVENTORY_ADJUST_STOCK: 'inventory.adjust.stock',
  INVENTORY_CREATE_ORDER: 'inventory.create.order',
  INVENTORY_APPROVE_ORDER: 'inventory.approve.order',
  INVENTORY_RECEIVE_ORDER: 'inventory.receive.order',
  INVENTORY_MANAGE_VENDORS: 'inventory.manage.vendors',
  INVENTORY_VIEW_REPORTS: 'inventory.view.reports',
  INVENTORY_DISPOSE: 'inventory.dispose',

  // Quality Control Permissions
  QC_VIEW_ALL: 'qc.view.all',
  QC_RUN_CONTROLS: 'qc.run.controls',
  QC_APPROVE_RESULTS: 'qc.approve.results',
  QC_MANAGE_RULES: 'qc.manage.rules',
  QC_VIEW_REPORTS: 'qc.view.reports',
  QC_OVERRIDE_FLAGS: 'qc.override.flags',
  QC_MANAGE_LOT: 'qc.manage.lot',
  QC_CALIBRATE_EQUIPMENT: 'qc.calibrate.equipment',

  // Reports & Analytics Permissions
  REPORTS_VIEW_CLINICAL: 'reports.view.clinical',
  REPORTS_VIEW_FINANCIAL: 'reports.view.financial',
  REPORTS_VIEW_OPERATIONAL: 'reports.view.operational',
  REPORTS_VIEW_QUALITY: 'reports.view.quality',
  REPORTS_CREATE_CUSTOM: 'reports.create.custom',
  REPORTS_EXPORT: 'reports.export',
  REPORTS_SCHEDULE: 'reports.schedule',
  REPORTS_VIEW_AUDIT: 'reports.view.audit',
  REPORTS_VIEW_COMPLIANCE: 'reports.view.compliance',

  // User Management Permissions
  USERS_VIEW_ALL: 'users.view.all',
  USERS_CREATE: 'users.create',
  USERS_UPDATE_ALL: 'users.update.all',
  USERS_UPDATE_OWN: 'users.update.own',
  USERS_DELETE: 'users.delete',
  USERS_ACTIVATE: 'users.activate',
  USERS_DEACTIVATE: 'users.deactivate',
  USERS_RESET_PASSWORD: 'users.reset.password',
  USERS_ASSIGN_ROLE: 'users.assign.role',
  USERS_MANAGE_PERMISSIONS: 'users.manage.permissions',
  USERS_IMPERSONATE: 'users.impersonate',
  USERS_VIEW_ACTIVITY: 'users.view.activity',

  // Settings & Configuration Permissions
  SETTINGS_VIEW_GENERAL: 'settings.view.general',
  SETTINGS_UPDATE_GENERAL: 'settings.update.general',
  SETTINGS_VIEW_CLINICAL: 'settings.view.clinical',
  SETTINGS_UPDATE_CLINICAL: 'settings.update.clinical',
  SETTINGS_MANAGE_TEMPLATES: 'settings.manage.templates',
  SETTINGS_MANAGE_WORKFLOWS: 'settings.manage.workflows',
  SETTINGS_MANAGE_INTEGRATIONS: 'settings.manage.integrations',
  SETTINGS_VIEW_AUDIT_LOG: 'settings.view.audit_log',
  SETTINGS_MANAGE_BACKUP: 'settings.manage.backup',
  SETTINGS_MANAGE_TENANT: 'settings.manage.tenant',

  // Equipment Management Permissions
  EQUIPMENT_VIEW_ALL: 'equipment.view.all',
  EQUIPMENT_CREATE: 'equipment.create',
  EQUIPMENT_UPDATE: 'equipment.update',
  EQUIPMENT_DELETE: 'equipment.delete',
  EQUIPMENT_SCHEDULE_MAINTENANCE: 'equipment.schedule.maintenance',
  EQUIPMENT_LOG_ISSUE: 'equipment.log.issue',
  EQUIPMENT_CALIBRATE: 'equipment.calibrate',

  // Home Collection Permissions
  HOME_COLLECTION_VIEW_ALL: 'home_collection.view.all',
  HOME_COLLECTION_VIEW_ASSIGNED: 'home_collection.view.assigned',
  HOME_COLLECTION_CREATE: 'home_collection.create',
  HOME_COLLECTION_UPDATE: 'home_collection.update',
  HOME_COLLECTION_ASSIGN: 'home_collection.assign',
  HOME_COLLECTION_COMPLETE: 'home_collection.complete',
  HOME_COLLECTION_CANCEL: 'home_collection.cancel',
  HOME_COLLECTION_VIEW_ROUTE: 'home_collection.view.route',

  // EMR Integration Permissions
  EMR_VIEW_CONNECTIONS: 'emr.view.connections',
  EMR_MANAGE_CONNECTIONS: 'emr.manage.connections',
  EMR_SYNC_DATA: 'emr.sync.data',
  EMR_VIEW_LOGS: 'emr.view.logs',
  EMR_CONFIGURE_MAPPING: 'emr.configure.mapping',

  // Admin & System Permissions
  ADMIN_ACCESS_PANEL: 'admin.access.panel',
  ADMIN_VIEW_SYSTEM_HEALTH: 'admin.view.system_health',
  ADMIN_MANAGE_TENANTS: 'admin.manage.tenants',
  ADMIN_VIEW_ALL_TENANTS: 'admin.view.all_tenants',
  ADMIN_SYSTEM_CONFIGURATION: 'admin.system.configuration',
  ADMIN_VIEW_LOGS: 'admin.view.logs',
  ADMIN_MANAGE_LICENSES: 'admin.manage.licenses',
  ADMIN_EMERGENCY_ACCESS: 'admin.emergency.access',
  ADMIN_DATA_MIGRATION: 'admin.data.migration',
  ADMIN_SYSTEM_MAINTENANCE: 'admin.system.maintenance',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Permission Categories for UI grouping
export const PERMISSION_CATEGORIES = {
  'Patient Management': [
    PERMISSIONS.PATIENTS_VIEW_ALL,
    PERMISSIONS.PATIENTS_VIEW_OWN,
    PERMISSIONS.PATIENTS_VIEW_ASSIGNED,
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.PATIENTS_UPDATE_ALL,
    PERMISSIONS.PATIENTS_UPDATE_OWN,
    PERMISSIONS.PATIENTS_DELETE,
    PERMISSIONS.PATIENTS_EXPORT,
    PERMISSIONS.PATIENTS_IMPORT,
    PERMISSIONS.PATIENTS_VIEW_MEDICAL_HISTORY,
    PERMISSIONS.PATIENTS_MERGE,
  ],
  'Test Management': [
    PERMISSIONS.TESTS_VIEW_ALL,
    PERMISSIONS.TESTS_VIEW_ASSIGNED,
    PERMISSIONS.TESTS_CREATE_ORDER,
    PERMISSIONS.TESTS_UPDATE_ORDER,
    PERMISSIONS.TESTS_CANCEL_ORDER,
    PERMISSIONS.TESTS_APPROVE_ORDER,
    PERMISSIONS.TESTS_MANAGE_CATALOG,
    PERMISSIONS.TESTS_CREATE_PANEL,
    PERMISSIONS.TESTS_UPDATE_PRICING,
    PERMISSIONS.TESTS_VIEW_PRICING,
    PERMISSIONS.TESTS_STAT_ORDER,
    PERMISSIONS.TESTS_BATCH_ORDER,
  ],
  'Sample Management': [
    PERMISSIONS.SAMPLES_COLLECT,
    PERMISSIONS.SAMPLES_RECEIVE,
    PERMISSIONS.SAMPLES_REJECT,
    PERMISSIONS.SAMPLES_PROCESS,
    PERMISSIONS.SAMPLES_TRACK,
    PERMISSIONS.SAMPLES_PRINT_BARCODE,
    PERMISSIONS.SAMPLES_ALIQUOT,
    PERMISSIONS.SAMPLES_DISPOSE,
    PERMISSIONS.SAMPLES_VIEW_ALL,
    PERMISSIONS.SAMPLES_UPDATE_STATUS,
  ],
  'Results Management': [
    PERMISSIONS.RESULTS_VIEW_ALL,
    PERMISSIONS.RESULTS_VIEW_ASSIGNED,
    PERMISSIONS.RESULTS_ENTER,
    PERMISSIONS.RESULTS_UPDATE,
    PERMISSIONS.RESULTS_VALIDATE,
    PERMISSIONS.RESULTS_APPROVE,
    PERMISSIONS.RESULTS_REJECT,
    PERMISSIONS.RESULTS_PRINT,
    PERMISSIONS.RESULTS_EMAIL,
    PERMISSIONS.RESULTS_AMEND,
    PERMISSIONS.RESULTS_VIEW_CRITICAL,
    PERMISSIONS.RESULTS_ACKNOWLEDGE_CRITICAL,
  ],
  'Billing & Insurance': [
    PERMISSIONS.BILLING_VIEW_ALL,
    PERMISSIONS.BILLING_VIEW_OWN,
    PERMISSIONS.BILLING_CREATE_INVOICE,
    PERMISSIONS.BILLING_UPDATE_INVOICE,
    PERMISSIONS.BILLING_CANCEL_INVOICE,
    PERMISSIONS.BILLING_APPLY_DISCOUNT,
    PERMISSIONS.BILLING_PROCESS_PAYMENT,
    PERMISSIONS.BILLING_PROCESS_REFUND,
    PERMISSIONS.BILLING_VIEW_REPORTS,
    PERMISSIONS.BILLING_MANAGE_INSURANCE,
    PERMISSIONS.BILLING_SUBMIT_CLAIM,
    PERMISSIONS.BILLING_MANAGE_PRICING,
    PERMISSIONS.BILLING_WRITE_OFF,
  ],
  'Inventory Management': [
    PERMISSIONS.INVENTORY_VIEW_ALL,
    PERMISSIONS.INVENTORY_VIEW_DEPARTMENT,
    PERMISSIONS.INVENTORY_ADD_STOCK,
    PERMISSIONS.INVENTORY_UPDATE_STOCK,
    PERMISSIONS.INVENTORY_TRANSFER_STOCK,
    PERMISSIONS.INVENTORY_ADJUST_STOCK,
    PERMISSIONS.INVENTORY_CREATE_ORDER,
    PERMISSIONS.INVENTORY_APPROVE_ORDER,
    PERMISSIONS.INVENTORY_RECEIVE_ORDER,
    PERMISSIONS.INVENTORY_MANAGE_VENDORS,
    PERMISSIONS.INVENTORY_VIEW_REPORTS,
    PERMISSIONS.INVENTORY_DISPOSE,
  ],
  'Quality Control': [
    PERMISSIONS.QC_VIEW_ALL,
    PERMISSIONS.QC_RUN_CONTROLS,
    PERMISSIONS.QC_APPROVE_RESULTS,
    PERMISSIONS.QC_MANAGE_RULES,
    PERMISSIONS.QC_VIEW_REPORTS,
    PERMISSIONS.QC_OVERRIDE_FLAGS,
    PERMISSIONS.QC_MANAGE_LOT,
    PERMISSIONS.QC_CALIBRATE_EQUIPMENT,
  ],
  'Reports & Analytics': [
    PERMISSIONS.REPORTS_VIEW_CLINICAL,
    PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    PERMISSIONS.REPORTS_VIEW_OPERATIONAL,
    PERMISSIONS.REPORTS_VIEW_QUALITY,
    PERMISSIONS.REPORTS_CREATE_CUSTOM,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.REPORTS_SCHEDULE,
    PERMISSIONS.REPORTS_VIEW_AUDIT,
    PERMISSIONS.REPORTS_VIEW_COMPLIANCE,
  ],
  'User Management': [
    PERMISSIONS.USERS_VIEW_ALL,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE_ALL,
    PERMISSIONS.USERS_UPDATE_OWN,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_ACTIVATE,
    PERMISSIONS.USERS_DEACTIVATE,
    PERMISSIONS.USERS_RESET_PASSWORD,
    PERMISSIONS.USERS_ASSIGN_ROLE,
    PERMISSIONS.USERS_MANAGE_PERMISSIONS,
    PERMISSIONS.USERS_IMPERSONATE,
    PERMISSIONS.USERS_VIEW_ACTIVITY,
  ],
  'Settings & Configuration': [
    PERMISSIONS.SETTINGS_VIEW_GENERAL,
    PERMISSIONS.SETTINGS_UPDATE_GENERAL,
    PERMISSIONS.SETTINGS_VIEW_CLINICAL,
    PERMISSIONS.SETTINGS_UPDATE_CLINICAL,
    PERMISSIONS.SETTINGS_MANAGE_TEMPLATES,
    PERMISSIONS.SETTINGS_MANAGE_WORKFLOWS,
    PERMISSIONS.SETTINGS_MANAGE_INTEGRATIONS,
    PERMISSIONS.SETTINGS_VIEW_AUDIT_LOG,
    PERMISSIONS.SETTINGS_MANAGE_BACKUP,
    PERMISSIONS.SETTINGS_MANAGE_TENANT,
  ],
  'Equipment Management': [
    PERMISSIONS.EQUIPMENT_VIEW_ALL,
    PERMISSIONS.EQUIPMENT_CREATE,
    PERMISSIONS.EQUIPMENT_UPDATE,
    PERMISSIONS.EQUIPMENT_DELETE,
    PERMISSIONS.EQUIPMENT_SCHEDULE_MAINTENANCE,
    PERMISSIONS.EQUIPMENT_LOG_ISSUE,
    PERMISSIONS.EQUIPMENT_CALIBRATE,
  ],
  'Home Collection': [
    PERMISSIONS.HOME_COLLECTION_VIEW_ALL,
    PERMISSIONS.HOME_COLLECTION_VIEW_ASSIGNED,
    PERMISSIONS.HOME_COLLECTION_CREATE,
    PERMISSIONS.HOME_COLLECTION_UPDATE,
    PERMISSIONS.HOME_COLLECTION_ASSIGN,
    PERMISSIONS.HOME_COLLECTION_COMPLETE,
    PERMISSIONS.HOME_COLLECTION_CANCEL,
    PERMISSIONS.HOME_COLLECTION_VIEW_ROUTE,
  ],
  'EMR Integration': [
    PERMISSIONS.EMR_VIEW_CONNECTIONS,
    PERMISSIONS.EMR_MANAGE_CONNECTIONS,
    PERMISSIONS.EMR_SYNC_DATA,
    PERMISSIONS.EMR_VIEW_LOGS,
    PERMISSIONS.EMR_CONFIGURE_MAPPING,
  ],
  'Admin & System': [
    PERMISSIONS.ADMIN_ACCESS_PANEL,
    PERMISSIONS.ADMIN_VIEW_SYSTEM_HEALTH,
    PERMISSIONS.ADMIN_MANAGE_TENANTS,
    PERMISSIONS.ADMIN_VIEW_ALL_TENANTS,
    PERMISSIONS.ADMIN_SYSTEM_CONFIGURATION,
    PERMISSIONS.ADMIN_VIEW_LOGS,
    PERMISSIONS.ADMIN_MANAGE_LICENSES,
    PERMISSIONS.ADMIN_EMERGENCY_ACCESS,
    PERMISSIONS.ADMIN_DATA_MIGRATION,
    PERMISSIONS.ADMIN_SYSTEM_MAINTENANCE,
  ],
} as const;

// Permission descriptions for UI
export const PERMISSION_DESCRIPTIONS: Record<Permission, string> = {
  // Patient Management
  [PERMISSIONS.PATIENTS_VIEW_ALL]: 'View all patients in the system',
  [PERMISSIONS.PATIENTS_VIEW_OWN]: 'View own patient records',
  [PERMISSIONS.PATIENTS_VIEW_ASSIGNED]: 'View assigned patients only',
  [PERMISSIONS.PATIENTS_CREATE]: 'Create new patient records',
  [PERMISSIONS.PATIENTS_UPDATE_ALL]: 'Update any patient record',
  [PERMISSIONS.PATIENTS_UPDATE_OWN]: 'Update own patient records',
  [PERMISSIONS.PATIENTS_DELETE]: 'Delete patient records',
  [PERMISSIONS.PATIENTS_EXPORT]: 'Export patient data',
  [PERMISSIONS.PATIENTS_IMPORT]: 'Import patient data',
  [PERMISSIONS.PATIENTS_VIEW_MEDICAL_HISTORY]: 'View complete medical history',
  [PERMISSIONS.PATIENTS_MERGE]: 'Merge duplicate patient records',

  // Test Management
  [PERMISSIONS.TESTS_VIEW_ALL]: 'View all test orders',
  [PERMISSIONS.TESTS_VIEW_ASSIGNED]: 'View assigned test orders',
  [PERMISSIONS.TESTS_CREATE_ORDER]: 'Create new test orders',
  [PERMISSIONS.TESTS_UPDATE_ORDER]: 'Update test orders',
  [PERMISSIONS.TESTS_CANCEL_ORDER]: 'Cancel test orders',
  [PERMISSIONS.TESTS_APPROVE_ORDER]: 'Approve test orders',
  [PERMISSIONS.TESTS_MANAGE_CATALOG]: 'Manage test catalog',
  [PERMISSIONS.TESTS_CREATE_PANEL]: 'Create test panels',
  [PERMISSIONS.TESTS_UPDATE_PRICING]: 'Update test pricing',
  [PERMISSIONS.TESTS_VIEW_PRICING]: 'View test pricing',
  [PERMISSIONS.TESTS_STAT_ORDER]: 'Create STAT/urgent orders',
  [PERMISSIONS.TESTS_BATCH_ORDER]: 'Create batch test orders',

  // Sample Management
  [PERMISSIONS.SAMPLES_COLLECT]: 'Collect patient samples',
  [PERMISSIONS.SAMPLES_RECEIVE]: 'Receive samples in lab',
  [PERMISSIONS.SAMPLES_REJECT]: 'Reject unsuitable samples',
  [PERMISSIONS.SAMPLES_PROCESS]: 'Process samples',
  [PERMISSIONS.SAMPLES_TRACK]: 'Track sample location',
  [PERMISSIONS.SAMPLES_PRINT_BARCODE]: 'Print sample barcodes',
  [PERMISSIONS.SAMPLES_ALIQUOT]: 'Create sample aliquots',
  [PERMISSIONS.SAMPLES_DISPOSE]: 'Dispose of samples',
  [PERMISSIONS.SAMPLES_VIEW_ALL]: 'View all samples',
  [PERMISSIONS.SAMPLES_UPDATE_STATUS]: 'Update sample status',

  // Results Management
  [PERMISSIONS.RESULTS_VIEW_ALL]: 'View all test results',
  [PERMISSIONS.RESULTS_VIEW_ASSIGNED]: 'View assigned test results',
  [PERMISSIONS.RESULTS_ENTER]: 'Enter test results',
  [PERMISSIONS.RESULTS_UPDATE]: 'Update test results',
  [PERMISSIONS.RESULTS_VALIDATE]: 'Validate test results',
  [PERMISSIONS.RESULTS_APPROVE]: 'Approve test results',
  [PERMISSIONS.RESULTS_REJECT]: 'Reject test results',
  [PERMISSIONS.RESULTS_PRINT]: 'Print test results',
  [PERMISSIONS.RESULTS_EMAIL]: 'Email test results',
  [PERMISSIONS.RESULTS_AMEND]: 'Amend approved results',
  [PERMISSIONS.RESULTS_VIEW_CRITICAL]: 'View critical results',
  [PERMISSIONS.RESULTS_ACKNOWLEDGE_CRITICAL]: 'Acknowledge critical results',

  // Billing & Insurance
  [PERMISSIONS.BILLING_VIEW_ALL]: 'View all billing records',
  [PERMISSIONS.BILLING_VIEW_OWN]: 'View own billing records',
  [PERMISSIONS.BILLING_CREATE_INVOICE]: 'Create invoices',
  [PERMISSIONS.BILLING_UPDATE_INVOICE]: 'Update invoices',
  [PERMISSIONS.BILLING_CANCEL_INVOICE]: 'Cancel invoices',
  [PERMISSIONS.BILLING_APPLY_DISCOUNT]: 'Apply discounts',
  [PERMISSIONS.BILLING_PROCESS_PAYMENT]: 'Process payments',
  [PERMISSIONS.BILLING_PROCESS_REFUND]: 'Process refunds',
  [PERMISSIONS.BILLING_VIEW_REPORTS]: 'View billing reports',
  [PERMISSIONS.BILLING_MANAGE_INSURANCE]: 'Manage insurance',
  [PERMISSIONS.BILLING_SUBMIT_CLAIM]: 'Submit insurance claims',
  [PERMISSIONS.BILLING_MANAGE_PRICING]: 'Manage pricing',
  [PERMISSIONS.BILLING_WRITE_OFF]: 'Write off bad debts',

  // Inventory Management
  [PERMISSIONS.INVENTORY_VIEW_ALL]: 'View all inventory',
  [PERMISSIONS.INVENTORY_VIEW_DEPARTMENT]: 'View department inventory',
  [PERMISSIONS.INVENTORY_ADD_STOCK]: 'Add new stock',
  [PERMISSIONS.INVENTORY_UPDATE_STOCK]: 'Update stock levels',
  [PERMISSIONS.INVENTORY_TRANSFER_STOCK]: 'Transfer stock',
  [PERMISSIONS.INVENTORY_ADJUST_STOCK]: 'Adjust stock counts',
  [PERMISSIONS.INVENTORY_CREATE_ORDER]: 'Create purchase orders',
  [PERMISSIONS.INVENTORY_APPROVE_ORDER]: 'Approve purchase orders',
  [PERMISSIONS.INVENTORY_RECEIVE_ORDER]: 'Receive orders',
  [PERMISSIONS.INVENTORY_MANAGE_VENDORS]: 'Manage vendors',
  [PERMISSIONS.INVENTORY_VIEW_REPORTS]: 'View inventory reports',
  [PERMISSIONS.INVENTORY_DISPOSE]: 'Dispose expired items',

  // Quality Control
  [PERMISSIONS.QC_VIEW_ALL]: 'View all QC data',
  [PERMISSIONS.QC_RUN_CONTROLS]: 'Run QC controls',
  [PERMISSIONS.QC_APPROVE_RESULTS]: 'Approve QC results',
  [PERMISSIONS.QC_MANAGE_RULES]: 'Manage QC rules',
  [PERMISSIONS.QC_VIEW_REPORTS]: 'View QC reports',
  [PERMISSIONS.QC_OVERRIDE_FLAGS]: 'Override QC flags',
  [PERMISSIONS.QC_MANAGE_LOT]: 'Manage control lots',
  [PERMISSIONS.QC_CALIBRATE_EQUIPMENT]: 'Calibrate equipment',

  // Reports & Analytics
  [PERMISSIONS.REPORTS_VIEW_CLINICAL]: 'View clinical reports',
  [PERMISSIONS.REPORTS_VIEW_FINANCIAL]: 'View financial reports',
  [PERMISSIONS.REPORTS_VIEW_OPERATIONAL]: 'View operational reports',
  [PERMISSIONS.REPORTS_VIEW_QUALITY]: 'View quality reports',
  [PERMISSIONS.REPORTS_CREATE_CUSTOM]: 'Create custom reports',
  [PERMISSIONS.REPORTS_EXPORT]: 'Export reports',
  [PERMISSIONS.REPORTS_SCHEDULE]: 'Schedule reports',
  [PERMISSIONS.REPORTS_VIEW_AUDIT]: 'View audit reports',
  [PERMISSIONS.REPORTS_VIEW_COMPLIANCE]: 'View compliance reports',

  // User Management
  [PERMISSIONS.USERS_VIEW_ALL]: 'View all users',
  [PERMISSIONS.USERS_CREATE]: 'Create new users',
  [PERMISSIONS.USERS_UPDATE_ALL]: 'Update any user',
  [PERMISSIONS.USERS_UPDATE_OWN]: 'Update own profile',
  [PERMISSIONS.USERS_DELETE]: 'Delete users',
  [PERMISSIONS.USERS_ACTIVATE]: 'Activate users',
  [PERMISSIONS.USERS_DEACTIVATE]: 'Deactivate users',
  [PERMISSIONS.USERS_RESET_PASSWORD]: 'Reset user passwords',
  [PERMISSIONS.USERS_ASSIGN_ROLE]: 'Assign user roles',
  [PERMISSIONS.USERS_MANAGE_PERMISSIONS]: 'Manage user permissions',
  [PERMISSIONS.USERS_IMPERSONATE]: 'Impersonate users',
  [PERMISSIONS.USERS_VIEW_ACTIVITY]: 'View user activity',

  // Settings & Configuration
  [PERMISSIONS.SETTINGS_VIEW_GENERAL]: 'View general settings',
  [PERMISSIONS.SETTINGS_UPDATE_GENERAL]: 'Update general settings',
  [PERMISSIONS.SETTINGS_VIEW_CLINICAL]: 'View clinical settings',
  [PERMISSIONS.SETTINGS_UPDATE_CLINICAL]: 'Update clinical settings',
  [PERMISSIONS.SETTINGS_MANAGE_TEMPLATES]: 'Manage templates',
  [PERMISSIONS.SETTINGS_MANAGE_WORKFLOWS]: 'Manage workflows',
  [PERMISSIONS.SETTINGS_MANAGE_INTEGRATIONS]: 'Manage integrations',
  [PERMISSIONS.SETTINGS_VIEW_AUDIT_LOG]: 'View audit logs',
  [PERMISSIONS.SETTINGS_MANAGE_BACKUP]: 'Manage backups',
  [PERMISSIONS.SETTINGS_MANAGE_TENANT]: 'Manage tenant settings',

  // Equipment Management
  [PERMISSIONS.EQUIPMENT_VIEW_ALL]: 'View all equipment',
  [PERMISSIONS.EQUIPMENT_CREATE]: 'Add new equipment',
  [PERMISSIONS.EQUIPMENT_UPDATE]: 'Update equipment',
  [PERMISSIONS.EQUIPMENT_DELETE]: 'Delete equipment',
  [PERMISSIONS.EQUIPMENT_SCHEDULE_MAINTENANCE]: 'Schedule maintenance',
  [PERMISSIONS.EQUIPMENT_LOG_ISSUE]: 'Log equipment issues',
  [PERMISSIONS.EQUIPMENT_CALIBRATE]: 'Calibrate equipment',

  // Home Collection
  [PERMISSIONS.HOME_COLLECTION_VIEW_ALL]: 'View all home collections',
  [PERMISSIONS.HOME_COLLECTION_VIEW_ASSIGNED]: 'View assigned collections',
  [PERMISSIONS.HOME_COLLECTION_CREATE]: 'Create home collection',
  [PERMISSIONS.HOME_COLLECTION_UPDATE]: 'Update home collection',
  [PERMISSIONS.HOME_COLLECTION_ASSIGN]: 'Assign phlebotomist',
  [PERMISSIONS.HOME_COLLECTION_COMPLETE]: 'Complete collection',
  [PERMISSIONS.HOME_COLLECTION_CANCEL]: 'Cancel collection',
  [PERMISSIONS.HOME_COLLECTION_VIEW_ROUTE]: 'View collection routes',

  // EMR Integration
  [PERMISSIONS.EMR_VIEW_CONNECTIONS]: 'View EMR connections',
  [PERMISSIONS.EMR_MANAGE_CONNECTIONS]: 'Manage EMR connections',
  [PERMISSIONS.EMR_SYNC_DATA]: 'Sync EMR data',
  [PERMISSIONS.EMR_VIEW_LOGS]: 'View EMR logs',
  [PERMISSIONS.EMR_CONFIGURE_MAPPING]: 'Configure field mapping',

  // Admin & System
  [PERMISSIONS.ADMIN_ACCESS_PANEL]: 'Access admin panel',
  [PERMISSIONS.ADMIN_VIEW_SYSTEM_HEALTH]: 'View system health',
  [PERMISSIONS.ADMIN_MANAGE_TENANTS]: 'Manage tenants',
  [PERMISSIONS.ADMIN_VIEW_ALL_TENANTS]: 'View all tenants',
  [PERMISSIONS.ADMIN_SYSTEM_CONFIGURATION]: 'System configuration',
  [PERMISSIONS.ADMIN_VIEW_LOGS]: 'View system logs',
  [PERMISSIONS.ADMIN_MANAGE_LICENSES]: 'Manage licenses',
  [PERMISSIONS.ADMIN_EMERGENCY_ACCESS]: 'Emergency access',
  [PERMISSIONS.ADMIN_DATA_MIGRATION]: 'Data migration',
  [PERMISSIONS.ADMIN_SYSTEM_MAINTENANCE]: 'System maintenance',
};