/**
 * Role-Permission Mapping for LabFlow System
 * Defines which permissions each role has by default
 */

import { PERMISSIONS, Permission } from './permissions.constants';
import { UserRole } from '../types/auth.types';

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  // Super Admin - Full system access
  super_admin: Object.values(PERMISSIONS),

  // Lab Admin - Full lab management except system admin
  lab_admin: [
    // Patient Management
    PERMISSIONS.PATIENTS_VIEW_ALL,
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.PATIENTS_UPDATE_ALL,
    PERMISSIONS.PATIENTS_DELETE,
    PERMISSIONS.PATIENTS_EXPORT,
    PERMISSIONS.PATIENTS_IMPORT,
    PERMISSIONS.PATIENTS_VIEW_MEDICAL_HISTORY,
    PERMISSIONS.PATIENTS_MERGE,

    // Test Management
    PERMISSIONS.TESTS_VIEW_ALL,
    PERMISSIONS.TESTS_CREATE_ORDER,
    PERMISSIONS.TESTS_UPDATE_ORDER,
    PERMISSIONS.TESTS_CANCEL_ORDER,
    PERMISSIONS.TESTS_APPROVE_ORDER,
    PERMISSIONS.TESTS_MANAGE_CATALOG,
    PERMISSIONS.TESTS_CREATE_PANEL,
    PERMISSIONS.TESTS_UPDATE_PRICING,
    PERMISSIONS.TESTS_VIEW_PRICING,
    PERMISSIONS.TESTS_STAT_ORDER,
    PERMISSIONS.TESTS_BATCH_ORDER,

    // Sample Management
    PERMISSIONS.SAMPLES_COLLECT,
    PERMISSIONS.SAMPLES_RECEIVE,
    PERMISSIONS.SAMPLES_REJECT,
    PERMISSIONS.SAMPLES_PROCESS,
    PERMISSIONS.SAMPLES_TRACK,
    PERMISSIONS.SAMPLES_PRINT_BARCODE,
    PERMISSIONS.SAMPLES_ALIQUOT,
    PERMISSIONS.SAMPLES_DISPOSE,
    PERMISSIONS.SAMPLES_VIEW_ALL,
    PERMISSIONS.SAMPLES_UPDATE_STATUS,

    // Results Management
    PERMISSIONS.RESULTS_VIEW_ALL,
    PERMISSIONS.RESULTS_ENTER,
    PERMISSIONS.RESULTS_UPDATE,
    PERMISSIONS.RESULTS_VALIDATE,
    PERMISSIONS.RESULTS_APPROVE,
    PERMISSIONS.RESULTS_REJECT,
    PERMISSIONS.RESULTS_PRINT,
    PERMISSIONS.RESULTS_EMAIL,
    PERMISSIONS.RESULTS_AMEND,
    PERMISSIONS.RESULTS_VIEW_CRITICAL,
    PERMISSIONS.RESULTS_ACKNOWLEDGE_CRITICAL,

    // Billing & Insurance
    PERMISSIONS.BILLING_VIEW_ALL,
    PERMISSIONS.BILLING_CREATE_INVOICE,
    PERMISSIONS.BILLING_UPDATE_INVOICE,
    PERMISSIONS.BILLING_CANCEL_INVOICE,
    PERMISSIONS.BILLING_APPLY_DISCOUNT,
    PERMISSIONS.BILLING_PROCESS_PAYMENT,
    PERMISSIONS.BILLING_PROCESS_REFUND,
    PERMISSIONS.BILLING_VIEW_REPORTS,
    PERMISSIONS.BILLING_MANAGE_INSURANCE,
    PERMISSIONS.BILLING_SUBMIT_CLAIM,
    PERMISSIONS.BILLING_MANAGE_PRICING,
    PERMISSIONS.BILLING_WRITE_OFF,

    // Inventory Management
    PERMISSIONS.INVENTORY_VIEW_ALL,
    PERMISSIONS.INVENTORY_ADD_STOCK,
    PERMISSIONS.INVENTORY_UPDATE_STOCK,
    PERMISSIONS.INVENTORY_TRANSFER_STOCK,
    PERMISSIONS.INVENTORY_ADJUST_STOCK,
    PERMISSIONS.INVENTORY_CREATE_ORDER,
    PERMISSIONS.INVENTORY_APPROVE_ORDER,
    PERMISSIONS.INVENTORY_RECEIVE_ORDER,
    PERMISSIONS.INVENTORY_MANAGE_VENDORS,
    PERMISSIONS.INVENTORY_VIEW_REPORTS,
    PERMISSIONS.INVENTORY_DISPOSE,

    // Quality Control
    PERMISSIONS.QC_VIEW_ALL,
    PERMISSIONS.QC_RUN_CONTROLS,
    PERMISSIONS.QC_APPROVE_RESULTS,
    PERMISSIONS.QC_MANAGE_RULES,
    PERMISSIONS.QC_VIEW_REPORTS,
    PERMISSIONS.QC_OVERRIDE_FLAGS,
    PERMISSIONS.QC_MANAGE_LOT,
    PERMISSIONS.QC_CALIBRATE_EQUIPMENT,

    // Reports & Analytics
    PERMISSIONS.REPORTS_VIEW_CLINICAL,
    PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    PERMISSIONS.REPORTS_VIEW_OPERATIONAL,
    PERMISSIONS.REPORTS_VIEW_QUALITY,
    PERMISSIONS.REPORTS_CREATE_CUSTOM,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.REPORTS_SCHEDULE,
    PERMISSIONS.REPORTS_VIEW_AUDIT,
    PERMISSIONS.REPORTS_VIEW_COMPLIANCE,

    // User Management
    PERMISSIONS.USERS_VIEW_ALL,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE_ALL,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_ACTIVATE,
    PERMISSIONS.USERS_DEACTIVATE,
    PERMISSIONS.USERS_RESET_PASSWORD,
    PERMISSIONS.USERS_ASSIGN_ROLE,
    PERMISSIONS.USERS_MANAGE_PERMISSIONS,
    PERMISSIONS.USERS_IMPERSONATE,
    PERMISSIONS.USERS_VIEW_ACTIVITY,

    // Settings & Configuration
    PERMISSIONS.SETTINGS_VIEW_GENERAL,
    PERMISSIONS.SETTINGS_UPDATE_GENERAL,
    PERMISSIONS.SETTINGS_VIEW_CLINICAL,
    PERMISSIONS.SETTINGS_UPDATE_CLINICAL,
    PERMISSIONS.SETTINGS_MANAGE_TEMPLATES,
    PERMISSIONS.SETTINGS_MANAGE_WORKFLOWS,
    PERMISSIONS.SETTINGS_MANAGE_INTEGRATIONS,
    PERMISSIONS.SETTINGS_VIEW_AUDIT_LOG,
    PERMISSIONS.SETTINGS_MANAGE_BACKUP,
    PERMISSIONS.SETTINGS_MANAGE_TENANT,

    // Equipment Management
    PERMISSIONS.EQUIPMENT_VIEW_ALL,
    PERMISSIONS.EQUIPMENT_CREATE,
    PERMISSIONS.EQUIPMENT_UPDATE,
    PERMISSIONS.EQUIPMENT_DELETE,
    PERMISSIONS.EQUIPMENT_SCHEDULE_MAINTENANCE,
    PERMISSIONS.EQUIPMENT_LOG_ISSUE,
    PERMISSIONS.EQUIPMENT_CALIBRATE,

    // Home Collection
    PERMISSIONS.HOME_COLLECTION_VIEW_ALL,
    PERMISSIONS.HOME_COLLECTION_CREATE,
    PERMISSIONS.HOME_COLLECTION_UPDATE,
    PERMISSIONS.HOME_COLLECTION_ASSIGN,
    PERMISSIONS.HOME_COLLECTION_COMPLETE,
    PERMISSIONS.HOME_COLLECTION_CANCEL,
    PERMISSIONS.HOME_COLLECTION_VIEW_ROUTE,

    // EMR Integration
    PERMISSIONS.EMR_VIEW_CONNECTIONS,
    PERMISSIONS.EMR_MANAGE_CONNECTIONS,
    PERMISSIONS.EMR_SYNC_DATA,
    PERMISSIONS.EMR_VIEW_LOGS,
    PERMISSIONS.EMR_CONFIGURE_MAPPING,

    // Admin Panel Access (limited)
    PERMISSIONS.ADMIN_ACCESS_PANEL,
    PERMISSIONS.ADMIN_VIEW_SYSTEM_HEALTH,
  ],

  // Lab Manager - Operational management
  lab_manager: [
    // Patient Management
    PERMISSIONS.PATIENTS_VIEW_ALL,
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.PATIENTS_UPDATE_ALL,
    PERMISSIONS.PATIENTS_EXPORT,
    PERMISSIONS.PATIENTS_VIEW_MEDICAL_HISTORY,

    // Test Management
    PERMISSIONS.TESTS_VIEW_ALL,
    PERMISSIONS.TESTS_CREATE_ORDER,
    PERMISSIONS.TESTS_UPDATE_ORDER,
    PERMISSIONS.TESTS_CANCEL_ORDER,
    PERMISSIONS.TESTS_APPROVE_ORDER,
    PERMISSIONS.TESTS_CREATE_PANEL,
    PERMISSIONS.TESTS_VIEW_PRICING,
    PERMISSIONS.TESTS_STAT_ORDER,
    PERMISSIONS.TESTS_BATCH_ORDER,

    // Sample Management
    PERMISSIONS.SAMPLES_COLLECT,
    PERMISSIONS.SAMPLES_RECEIVE,
    PERMISSIONS.SAMPLES_REJECT,
    PERMISSIONS.SAMPLES_PROCESS,
    PERMISSIONS.SAMPLES_TRACK,
    PERMISSIONS.SAMPLES_PRINT_BARCODE,
    PERMISSIONS.SAMPLES_ALIQUOT,
    PERMISSIONS.SAMPLES_VIEW_ALL,
    PERMISSIONS.SAMPLES_UPDATE_STATUS,

    // Results Management
    PERMISSIONS.RESULTS_VIEW_ALL,
    PERMISSIONS.RESULTS_ENTER,
    PERMISSIONS.RESULTS_UPDATE,
    PERMISSIONS.RESULTS_VALIDATE,
    PERMISSIONS.RESULTS_APPROVE,
    PERMISSIONS.RESULTS_PRINT,
    PERMISSIONS.RESULTS_EMAIL,
    PERMISSIONS.RESULTS_VIEW_CRITICAL,
    PERMISSIONS.RESULTS_ACKNOWLEDGE_CRITICAL,

    // Billing & Insurance
    PERMISSIONS.BILLING_VIEW_ALL,
    PERMISSIONS.BILLING_CREATE_INVOICE,
    PERMISSIONS.BILLING_UPDATE_INVOICE,
    PERMISSIONS.BILLING_APPLY_DISCOUNT,
    PERMISSIONS.BILLING_PROCESS_PAYMENT,
    PERMISSIONS.BILLING_VIEW_REPORTS,

    // Inventory Management
    PERMISSIONS.INVENTORY_VIEW_ALL,
    PERMISSIONS.INVENTORY_ADD_STOCK,
    PERMISSIONS.INVENTORY_UPDATE_STOCK,
    PERMISSIONS.INVENTORY_TRANSFER_STOCK,
    PERMISSIONS.INVENTORY_CREATE_ORDER,
    PERMISSIONS.INVENTORY_RECEIVE_ORDER,
    PERMISSIONS.INVENTORY_VIEW_REPORTS,

    // Quality Control
    PERMISSIONS.QC_VIEW_ALL,
    PERMISSIONS.QC_RUN_CONTROLS,
    PERMISSIONS.QC_APPROVE_RESULTS,
    PERMISSIONS.QC_VIEW_REPORTS,
    PERMISSIONS.QC_MANAGE_LOT,

    // Reports & Analytics
    PERMISSIONS.REPORTS_VIEW_CLINICAL,
    PERMISSIONS.REPORTS_VIEW_OPERATIONAL,
    PERMISSIONS.REPORTS_VIEW_QUALITY,
    PERMISSIONS.REPORTS_EXPORT,

    // User Management (limited)
    PERMISSIONS.USERS_VIEW_ALL,
    PERMISSIONS.USERS_UPDATE_OWN,
    PERMISSIONS.USERS_VIEW_ACTIVITY,

    // Settings & Configuration (view only)
    PERMISSIONS.SETTINGS_VIEW_GENERAL,
    PERMISSIONS.SETTINGS_VIEW_CLINICAL,

    // Equipment Management
    PERMISSIONS.EQUIPMENT_VIEW_ALL,
    PERMISSIONS.EQUIPMENT_UPDATE,
    PERMISSIONS.EQUIPMENT_SCHEDULE_MAINTENANCE,
    PERMISSIONS.EQUIPMENT_LOG_ISSUE,

    // Home Collection
    PERMISSIONS.HOME_COLLECTION_VIEW_ALL,
    PERMISSIONS.HOME_COLLECTION_ASSIGN,
    PERMISSIONS.HOME_COLLECTION_VIEW_ROUTE,
  ],

  // Lab Technician - Test processing and results
  lab_technician: [
    // Patient Management (limited)
    PERMISSIONS.PATIENTS_VIEW_ASSIGNED,
    PERMISSIONS.PATIENTS_VIEW_MEDICAL_HISTORY,

    // Test Management (limited)
    PERMISSIONS.TESTS_VIEW_ASSIGNED,
    PERMISSIONS.TESTS_UPDATE_ORDER,
    PERMISSIONS.TESTS_VIEW_PRICING,

    // Sample Management
    PERMISSIONS.SAMPLES_RECEIVE,
    PERMISSIONS.SAMPLES_PROCESS,
    PERMISSIONS.SAMPLES_TRACK,
    PERMISSIONS.SAMPLES_PRINT_BARCODE,
    PERMISSIONS.SAMPLES_ALIQUOT,
    PERMISSIONS.SAMPLES_VIEW_ALL,
    PERMISSIONS.SAMPLES_UPDATE_STATUS,

    // Results Management
    PERMISSIONS.RESULTS_VIEW_ASSIGNED,
    PERMISSIONS.RESULTS_ENTER,
    PERMISSIONS.RESULTS_UPDATE,
    PERMISSIONS.RESULTS_VALIDATE,
    PERMISSIONS.RESULTS_VIEW_CRITICAL,

    // Quality Control
    PERMISSIONS.QC_VIEW_ALL,
    PERMISSIONS.QC_RUN_CONTROLS,
    PERMISSIONS.QC_VIEW_REPORTS,

    // Inventory (view only)
    PERMISSIONS.INVENTORY_VIEW_DEPARTMENT,

    // Equipment
    PERMISSIONS.EQUIPMENT_VIEW_ALL,
    PERMISSIONS.EQUIPMENT_LOG_ISSUE,

    // User Management (self only)
    PERMISSIONS.USERS_UPDATE_OWN,
  ],

  // Phlebotomist - Sample collection
  phlebotomist: [
    // Patient Management (limited)
    PERMISSIONS.PATIENTS_VIEW_ASSIGNED,
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.PATIENTS_UPDATE_OWN,

    // Test Management (view only)
    PERMISSIONS.TESTS_VIEW_ASSIGNED,

    // Sample Management
    PERMISSIONS.SAMPLES_COLLECT,
    PERMISSIONS.SAMPLES_TRACK,
    PERMISSIONS.SAMPLES_PRINT_BARCODE,
    PERMISSIONS.SAMPLES_UPDATE_STATUS,

    // Home Collection
    PERMISSIONS.HOME_COLLECTION_VIEW_ASSIGNED,
    PERMISSIONS.HOME_COLLECTION_UPDATE,
    PERMISSIONS.HOME_COLLECTION_COMPLETE,
    PERMISSIONS.HOME_COLLECTION_VIEW_ROUTE,

    // User Management (self only)
    PERMISSIONS.USERS_UPDATE_OWN,
  ],

  // Pathologist - Medical review and approval
  pathologist: [
    // Patient Management
    PERMISSIONS.PATIENTS_VIEW_ALL,
    PERMISSIONS.PATIENTS_VIEW_MEDICAL_HISTORY,

    // Test Management
    PERMISSIONS.TESTS_VIEW_ALL,
    PERMISSIONS.TESTS_APPROVE_ORDER,

    // Sample Management (view only)
    PERMISSIONS.SAMPLES_VIEW_ALL,
    PERMISSIONS.SAMPLES_TRACK,

    // Results Management
    PERMISSIONS.RESULTS_VIEW_ALL,
    PERMISSIONS.RESULTS_VALIDATE,
    PERMISSIONS.RESULTS_APPROVE,
    PERMISSIONS.RESULTS_REJECT,
    PERMISSIONS.RESULTS_AMEND,
    PERMISSIONS.RESULTS_VIEW_CRITICAL,
    PERMISSIONS.RESULTS_ACKNOWLEDGE_CRITICAL,

    // Quality Control
    PERMISSIONS.QC_VIEW_ALL,
    PERMISSIONS.QC_APPROVE_RESULTS,
    PERMISSIONS.QC_VIEW_REPORTS,
    PERMISSIONS.QC_OVERRIDE_FLAGS,

    // Reports
    PERMISSIONS.REPORTS_VIEW_CLINICAL,
    PERMISSIONS.REPORTS_VIEW_QUALITY,
    PERMISSIONS.REPORTS_EXPORT,

    // User Management (self only)
    PERMISSIONS.USERS_UPDATE_OWN,
  ],

  // Radiologist - Imaging review
  radiologist: [
    // Patient Management
    PERMISSIONS.PATIENTS_VIEW_ALL,
    PERMISSIONS.PATIENTS_VIEW_MEDICAL_HISTORY,

    // Test Management (imaging tests)
    PERMISSIONS.TESTS_VIEW_ASSIGNED,
    PERMISSIONS.TESTS_APPROVE_ORDER,

    // Results Management
    PERMISSIONS.RESULTS_VIEW_ASSIGNED,
    PERMISSIONS.RESULTS_ENTER,
    PERMISSIONS.RESULTS_UPDATE,
    PERMISSIONS.RESULTS_VALIDATE,
    PERMISSIONS.RESULTS_APPROVE,
    PERMISSIONS.RESULTS_VIEW_CRITICAL,
    PERMISSIONS.RESULTS_ACKNOWLEDGE_CRITICAL,

    // Reports
    PERMISSIONS.REPORTS_VIEW_CLINICAL,
    PERMISSIONS.REPORTS_EXPORT,

    // User Management (self only)
    PERMISSIONS.USERS_UPDATE_OWN,
  ],

  // Billing Staff - Financial operations
  billing_staff: [
    // Patient Management (limited)
    PERMISSIONS.PATIENTS_VIEW_ALL,
    PERMISSIONS.PATIENTS_CREATE,

    // Test Management (pricing)
    PERMISSIONS.TESTS_VIEW_ALL,
    PERMISSIONS.TESTS_VIEW_PRICING,

    // Results (for billing verification)
    PERMISSIONS.RESULTS_VIEW_ALL,
    PERMISSIONS.RESULTS_PRINT,

    // Billing & Insurance
    PERMISSIONS.BILLING_VIEW_ALL,
    PERMISSIONS.BILLING_CREATE_INVOICE,
    PERMISSIONS.BILLING_UPDATE_INVOICE,
    PERMISSIONS.BILLING_CANCEL_INVOICE,
    PERMISSIONS.BILLING_APPLY_DISCOUNT,
    PERMISSIONS.BILLING_PROCESS_PAYMENT,
    PERMISSIONS.BILLING_PROCESS_REFUND,
    PERMISSIONS.BILLING_VIEW_REPORTS,
    PERMISSIONS.BILLING_MANAGE_INSURANCE,
    PERMISSIONS.BILLING_SUBMIT_CLAIM,

    // Reports
    PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    PERMISSIONS.REPORTS_EXPORT,

    // User Management (self only)
    PERMISSIONS.USERS_UPDATE_OWN,
  ],

  // Front Desk - Reception and basic operations
  front_desk: [
    // Patient Management
    PERMISSIONS.PATIENTS_VIEW_ALL,
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.PATIENTS_UPDATE_ALL,

    // Test Management
    PERMISSIONS.TESTS_VIEW_ALL,
    PERMISSIONS.TESTS_CREATE_ORDER,
    PERMISSIONS.TESTS_UPDATE_ORDER,
    PERMISSIONS.TESTS_VIEW_PRICING,

    // Sample Management (limited)
    PERMISSIONS.SAMPLES_PRINT_BARCODE,
    PERMISSIONS.SAMPLES_TRACK,

    // Results (printing only)
    PERMISSIONS.RESULTS_VIEW_ALL,
    PERMISSIONS.RESULTS_PRINT,

    // Billing (basic)
    PERMISSIONS.BILLING_VIEW_ALL,
    PERMISSIONS.BILLING_CREATE_INVOICE,
    PERMISSIONS.BILLING_PROCESS_PAYMENT,

    // Home Collection
    PERMISSIONS.HOME_COLLECTION_VIEW_ALL,
    PERMISSIONS.HOME_COLLECTION_CREATE,
    PERMISSIONS.HOME_COLLECTION_UPDATE,

    // User Management (self only)
    PERMISSIONS.USERS_UPDATE_OWN,
  ],

  // Clinician - Medical practice
  clinician: [
    // Patient Management
    PERMISSIONS.PATIENTS_VIEW_ASSIGNED,
    PERMISSIONS.PATIENTS_UPDATE_OWN,
    PERMISSIONS.PATIENTS_VIEW_MEDICAL_HISTORY,

    // Test Management
    PERMISSIONS.TESTS_VIEW_ASSIGNED,
    PERMISSIONS.TESTS_CREATE_ORDER,
    PERMISSIONS.TESTS_UPDATE_ORDER,
    PERMISSIONS.TESTS_STAT_ORDER,

    // Results
    PERMISSIONS.RESULTS_VIEW_ASSIGNED,
    PERMISSIONS.RESULTS_PRINT,
    PERMISSIONS.RESULTS_VIEW_CRITICAL,

    // Reports
    PERMISSIONS.REPORTS_VIEW_CLINICAL,
    PERMISSIONS.REPORTS_EXPORT,

    // EMR Integration
    PERMISSIONS.EMR_VIEW_CONNECTIONS,
    PERMISSIONS.EMR_SYNC_DATA,

    // User Management (self only)
    PERMISSIONS.USERS_UPDATE_OWN,
  ],

  // Patient - End user
  patient: [
    // Patient Management (self only)
    PERMISSIONS.PATIENTS_VIEW_OWN,
    PERMISSIONS.PATIENTS_UPDATE_OWN,

    // Test Management (own tests)
    PERMISSIONS.TESTS_VIEW_ASSIGNED,

    // Results (own results)
    PERMISSIONS.RESULTS_VIEW_ASSIGNED,
    PERMISSIONS.RESULTS_PRINT,

    // Billing (own bills)
    PERMISSIONS.BILLING_VIEW_OWN,

    // Home Collection (own requests)
    PERMISSIONS.HOME_COLLECTION_VIEW_ASSIGNED,
    PERMISSIONS.HOME_COLLECTION_CREATE,
    PERMISSIONS.HOME_COLLECTION_UPDATE,
    PERMISSIONS.HOME_COLLECTION_CANCEL,

    // User Management (self only)
    PERMISSIONS.USERS_UPDATE_OWN,
  ],
};

// Helper function to get all permissions for a role
export function getRolePermissions(role: UserRole): Permission[] {
  return ROLE_PERMISSIONS[role] || [];
}

// Helper function to check if a role has a specific permission
export function roleHasPermission(role: UserRole, permission: Permission): boolean {
  return getRolePermissions(role).includes(permission);
}

// Get all unique permissions across all roles
export function getAllPermissions(): Permission[] {
  const allPermissions = new Set<Permission>();
  Object.values(ROLE_PERMISSIONS).forEach(permissions => {
    permissions.forEach(permission => allPermissions.add(permission));
  });
  return Array.from(allPermissions);
}

// Get roles that have a specific permission
export function getRolesWithPermission(permission: Permission): UserRole[] {
  return (Object.keys(ROLE_PERMISSIONS) as UserRole[]).filter(role => 
    roleHasPermission(role, permission)
  );
}