// Pakistan Cities Data
export const pakistanCities: Record<string, string[]> = {
  'Punjab': [
    'Lahore',
    'Faisalabad',
    'Rawalpindi',
    'Multan',
    'Gujranwala',
    'Islamabad',
    'Sargodha',
    'Bahawalpur',
    'Sialkot',
    'Sheikhupura',
    'Jhang',
    'Dera Ghazi Khan',
    'Gujrat',
    'Sahiwal',
    'Wah Cantonment',
    'Kasur',
    'Rahim Yar Khan',
    'Okara',
    'Wazirabad',
    'Hafizabad',
    'Sadiqabad',
    'Jhelum',
    'Khanewal',
    'Mandi Bahauddin',
    'Pakpattan',
    'Vehari',
    'Chakwal',
    'Mianwali',
    'Chiniot',
    'Kamoke',
    'Attock',
    'Muridke',
    'Khushab',
    'Jaranwala',
    'Burewala',
    'Daska',
    'Muzaffargarh',
    'Arifwala',
    'Bahawalnagar',
    'Kot Addu',
    'Toba Tek Singh'
  ],
  'Sindh': [
    'Karachi',
    'Hyderabad',
    'Sukkur',
    'Larkana',
    'Nawabshah',
    'Mirpur Khas',
    'Jacobabad',
    'Shikarpur',
    'Khairpur',
    'Dadu',
    'Kotri',
    'Jamshoro',
    'Bhiria',
    'Kandhkot',
    'Mehrabpur',
    'Sehwan',
    'Thatta',
    'Badin',
    'Tando Adam',
    'Tando Muhammad Khan',
    'Umerkot',
    'Mithi',
    'Sanghar',
    'Tando Allahyar',
    'Naushahro Feroze',
    'Shahdadpur',
    'Matiari',
    'Kambar',
    'Ghotki',
    'Rohri'
  ],
  'Khyber Pakhtunkhwa': [
    'Peshawar',
    'Mardan',
    'Mingora',
    'Kohat',
    'Abbottabad',
    'Mansehra',
    'Swabi',
    'Nowshera',
    'Charsadda',
    'Dera Ismail Khan',
    'Haripur',
    'Swat',
    'Bannu',
    'Karak',
    'Lakki Marwat',
    'Hangu',
    'Tank',
    'Chitral',
    'Dir',
    'Buner',
    'Shangla',
    'Batagram',
    'Kohistan',
    'Tor Ghar',
    'Malakand'
  ],
  'Balochistan': [
    'Quetta',
    'Turbat',
    'Khuzdar',
    'Gwadar',
    'Sibi',
    'Chaman',
    'Zhob',
    'Dera Murad Jamali',
    'Dera Allah Yar',
    'Mastung',
    'Kalat',
    'Nushki',
    'Kharan',
    'Pishin',
    'Loralai',
    'Bela',
    'Pasni',
    'Jiwani',
    'Ormara',
    'Uthal',
    'Gandava',
    'Jhal Magsi',
    'Naseerabad',
    'Barkhan'
  ],
  'Azad Kashmir': [
    'Muzaffarabad',
    'Mirpur',
    'Rawalakot',
    'Kotli',
    'Bhimber',
    'Bagh',
    'Pallandri',
    'Sudhanoti',
    'Haveli',
    'Neelum'
  ],
  'Gilgit-Baltistan': [
    'Gilgit',
    'Skardu',
    'Hunza',
    'Nagar',
    'Ghanche',
    'Shigar',
    'Astore',
    'Diamer',
    'Ghizer',
    'Gupis-Yasin',
    'Kharmang',
    'Rondu'
  ],
  'Islamabad Capital Territory': [
    'Islamabad'
  ]
};

// Get cities for a state
export const getCitiesForState = (state: string): string[] => {
  return pakistanCities[state] || [];
};

// Get all Pakistani states
export const getPakistanStates = (): string[] => {
  return Object.keys(pakistanCities);
};