require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunitySpeechRecognition', :path => '../../node_modules/@capacitor-community/speech-recognition'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorDevice', :path => '../../node_modules/@capacitor/device'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorGeolocation', :path => '../../node_modules/@capacitor/geolocation'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorNetwork', :path => '../../node_modules/@capacitor/network'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
  pod 'CapacitorShare', :path => '../../node_modules/@capacitor/share'
  pod 'BuildkitUi', :path => '../../node_modules/buildkit-ui'
  pod 'CapacitorAuthManager', :path => '../../node_modules/capacitor-auth-manager'
  pod 'CapacitorBiometricAuthentication', :path => '../../node_modules/capacitor-biometric-authentication'
  pod 'CapacitorFirebaseKit', :path => '../../node_modules/capacitor-firebase-kit'
  pod 'CapacitorNativeUpdate', :path => '../../node_modules/capacitor-native-update'
  pod 'CodeCraftStudio', :path => '../../node_modules/code-craft-studio'
  pod 'QrcodeStudio', :path => '../../node_modules/qrcode-studio'
  pod 'StrataStorage', :path => '../../node_modules/strata-storage'
  pod 'UnifiedTracking', :path => '../../node_modules/unified-tracking'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
